package com.app.ecom.service;

import com.app.ecom.dto.OrderItemDTO;
import com.app.ecom.dto.OrderResponse;
import com.app.ecom.model.*;
import com.app.ecom.repository.OrderRepository;
import com.app.ecom.repository.UserRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

import java.math.BigDecimal;
import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;

/**
 * ====================================================================
 * 🧾 OrderService — Core Business Logic for Order Creation and Mapping
 * ====================================================================
 *
 * This service handles the complete workflow of placing an order:
 *  • Validates user and cart data.
 *  • Calculates total payable amount.
 *  • Creates an Order with related OrderItems.
 *  • Saves data to the database.
 *  • Clears the user's cart after successful order placement.
 *  • Returns a well-structured response DTO for the API layer.
 *
 * Architectural Role:
 *  - Controller → receives user request.
 *  - Service (this class) → performs business logic.
 *  - Repository → interacts with database.
 *
 * Dependency Injection:
 *  - Managed by Lombok's @RequiredArgsConstructor.
 *  - Ensures immutability and cleaner testing setup.
 */
@Service
@RequiredArgsConstructor
public class OrderService {

    /** Injected service and repository dependencies */
    private final CartService cartService;
    private final UserRepository userRepository;
    private final OrderRepository orderRepository;

    // ----------------------------------------------------------------------
    // 🔹 createOrder() — Creates and saves an order for the given user
    // ----------------------------------------------------------------------

    /**
     * Creates a new order for the specified user.
     *
     * <p><b>Process Flow:</b></p>
     *  1️⃣ Validate that the user and cart exist. <br>
     *  2️⃣ Calculate total order amount. <br>
     *  3️⃣ Create an Order and associated OrderItems. <br>
     *  4️⃣ Save order data to the database. <br>
     *  5️⃣ Clear the user’s cart after successful order creation. <br>
     *  6️⃣ Return an OrderResponse DTO for the API.
     *
     * @param userId ID of the user placing the order (passed in request header)
     * @return Optional<OrderResponse> — empty if cart or user invalid, else order details.
     */
    public Optional<OrderResponse> createOrder(String userId) {

        // Step 1️⃣ — Fetch all cart items for the user
        List<CartItem> cartItems = cartService.getCart(userId);

        // If cart is empty, order cannot be created
        if (cartItems.isEmpty()) {
            return Optional.empty();
        }

        // Step 2️⃣ — Validate that the user exists
        Optional<User> userOptional = userRepository.findById(Long.parseLong(userId));
        if (userOptional.isEmpty()) {
            return Optional.empty();
        }

        User user = userOptional.get();

        // Step 3️⃣ — Calculate total order amount = Σ(price × quantity)
        BigDecimal totalPrice = cartItems.stream()
                .map(item -> item.getPrice().multiply(BigDecimal.valueOf(item.getQuantity())))
                .reduce(BigDecimal.ZERO, BigDecimal::add);

        // Step 4️⃣ — Create and populate Order entity
        Order order = new Order();
        order.setUser(user);
        order.setStatus(OrderStatus.CONFIRMED); // Default status when order is placed
        order.setTotalAmount(totalPrice);

        // Step 5️⃣ — Convert CartItems → OrderItems
        List<OrderItem> orderItems = cartItems.stream()
                .map(item -> new OrderItem(
                        null,                      // Primary key is auto-generated by JPA
                        item.getProduct(),          // Product associated with the order
                        item.getQuantity(),         // Quantity purchased
                        item.getPrice(),            // Unit price at time of order
                        order                       // Associate order with each item
                ))
                .collect(Collectors.toList());

        order.setItems(orderItems);

        // Step 6️⃣ — Persist the order in the database
        // JPA cascade ensures that OrderItems are saved along with the Order
        Order savedOrder = orderRepository.save(order);

        // Step 7️⃣ — Clear user’s cart after successful order creation
        cartService.clearCart(userId);

        // Step 8️⃣ — Return a mapped DTO with all order details
        return Optional.of(mapToOrderResponse(savedOrder));
    }

    // ----------------------------------------------------------------------
    // 🔹 mapToOrderResponse() — Converts Order entity → OrderResponse DTO
    // ----------------------------------------------------------------------

    /**
     * Converts an {@link Order} entity into an {@link OrderResponse} DTO
     * for clean API responses. Each {@link OrderItem} is mapped to
     * a lightweight {@link OrderItemDTO}.
     *
     * <p><b>Purpose:</b></p>
     *  • Prevents exposing internal JPA entities to the frontend. <br>
     *  • Simplifies serialization. <br>
     *  • Provides a concise and structured order summary.
     *
     * @param order The saved Order entity.
     * @return An OrderResponse containing summarized order details.
     */
    private OrderResponse mapToOrderResponse(Order order) {

        // Convert each OrderItem → OrderItemDTO
        List<OrderItemDTO> itemDTOs = order.getItems().stream()
                .map(oi -> new OrderItemDTO(
                        oi.getId(),                                // Unique item ID
                        oi.getProduct().getId(),                   // Product ID
                        oi.getQuantity(),                          // Ordered quantity
                        oi.getPrice(),                             // Unit price
                        oi.getPrice().multiply(BigDecimal.valueOf(oi.getQuantity())) // Subtotal
                ))
                .collect(Collectors.toList());

        // Return final OrderResponse DTO with all essential fields
        return new OrderResponse(
                order.getId(),             // Order ID
                order.getTotalAmount(),    // Total amount
                order.getStatus(),         // Current order status
                itemDTOs,                  // List of order items
                order.getCreatedAt(),      // Creation timestamp
                order.getUpdatedAt()       // Last modification timestamp
        );
    }
}
